### ISSUE TITLE
The bot doesn't seem to be working

### ISSUE THREAD

**Issue by VoltIcaRus** [jckli/picsiv#2]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/bluebot/pixiv/cogs/main.py", line 23, in on_message
    data = pixiv.parse_hibiapi(json)
  File "/home/ubuntu/bluebot/pixiv/core/pixiv.py", line 35, in parse_hibiapi
    data = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/bluebot/pixiv/cogs/main.py", line 23, in on_message
    data = pixiv.parse_hibiapi(json)
  File "/home/ubuntu/bluebot/pixiv/core/pixiv.py", line 35, in parse_hibiapi
    data = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

It seems that https://jackli.dev/picsiv has stopped working as well as the bot I personally fork.
Any ideas?

**Comment by jckli** [comment]
uh oh. That’s no good. I think I know the error though and I’ll implement a fix shortly.

Thanks for the report.

**Comment by jckli** [comment]
Alright, with the commit 6526816bd2857e21d310ca80a74f32557fffe93f, the issue should be fixed. Try it out.

For the future, this error was caused because the hosted instance of the API that I use, HibiAPI, went down. I'm probably going to change it again in the near future to one that I personally manage and self-host, as currently, I use just random instances online lol.

**Comment by VoltIcaRus** [comment]
api.imki .moe doesn't seem to return the correct values

Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 382, in _run_event
     await coro(*args, **kwargs)
   File "/home/ubuntu/bluebot/pixiv/cogs/main.py", line 23, in on_message
     data = pixiv.parse_hibiapi(json)
   File "/home/ubuntu/bluebot/pixiv/core/pixiv.py", line 36, in parse_hibiapi
     illust = data["illust"]
KeyError: 'illust'

{"error":{"user_message":"","message":"Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant","reason":"","user_message_details" :{}}}

This is the value that appears when requesting an illustration id.

The solution is self-hosting the HibiAPI?

**Comment by jckli** [comment]
Hmm. I can't find any more hosted versions of HibiAPI so I can't make a hotfix right now. I'll be able to host an instance of HibiAPI when I get home though.

> The solution is self-hosting the HibiAPI?

Yeah, the best solution is for me to self-host the API, as then I can personally manage and fix errors. I don't particularly appreciate dealing with other people's instances going down or not being handled correctly.

Sorry for the inconveniences

**Comment by jckli** [comment]
Alright, I'm self-hosting my own instance now. Issue fixed for the actual Picsiv bot.
Just sync your fork with this repo again and everything should work again. Sorry again for the inconvenience.
